### ISSUE TITLE
Custom Zip

### ISSUE THREAD

**Issue by lbrictson** [tmaiaroto/aegis#26]
Is it possible to create a custom zip and include non go files like templates and such?

I saw in the config file that you can provide a custom zip file, which i created by generating the go binary and placing it in a zip with my template but no dice.

Any suggestions?

**Comment by lbrictson** [comment]
Apologies, I read through the code and saw that my mistake was not setting the name of the go binary correctly.  Got it all sorted out!

**Comment by tmaiaroto** [comment]
Yea, there's the option to specify a specific zip file. That would leave you on the hook for building and zipping the binary and all the assets yourself rather than letting the deploy command doing it for you. I wanted to leave that flexibility in there for these kinda scenarios.

Typically I use something like go-bindata to embed assets into the binary itself...But you can of course include other files in the zip file.

Since AWS supported Go natively, there are actually no files to zip up other than the binary now. It may be worthwhile to specify some sort of "assets" directory to also include in the zip file wholesale. Or a key in the yaml with an array of files underneath perhaps (more typing to do in your config).

Please feel free to open an issue requesting that if you find it useful or submit a pull request. It's something that would make sense in the deploy command. It's just something I never needed.
