### ISSUE TITLE
token contains an invalid number of segments

### ISSUE THREAD

**Issue by agorman** [tmaiaroto/aegis#34]
I'm hitting this error in the cognito callback function. Looks like it's coming from here https://github.com/tmaiaroto/aegis/blob/master/framework/cognito_client.go#L287

**Comment by agorman** [comment]
The issue is actually here. 
https://github.com/tmaiaroto/aegis/blob/master/framework/cognito_client.go#L254

I get the following response body.

```
{
    "error": "invalid_grant"
}
```

It decodes properly and continues without error. but the Token.IDToken field is blank. I updated my grants and it works now. Might be worth checking the response code to catch the error.

**Comment by tmaiaroto** [comment]
Have you set up your Cognito pool?
The example will try to figure out the well known keys and everything else
based on the user pool ID and also the client ID. Take a look at the readme.

And if so, how do you have your pool set up?

**Comment by tmaiaroto** [comment]
Definitely will, thanks. And thank you for testing this all out and bearing
with me on the issues, it really helps.

**Comment by tmaiaroto** [comment]
Can you let me know the options you had for your Cognito client app? It'll let me test this better.

For now, I've included an `Error` field in the `CognitoToken` struct so that it will take the "error" from the response body and put it somewhere accessible to your code. I've also updated the Cognito example to reflect how you'd do this. https://github.com/tmaiaroto/aegis/blob/master/examples/cognito/main.go#L90

So handlers can now more easily do something about this situation. I may need to adjust the service itself to handle more types of auth flows or distinctly label things to make sure it's clear about the _authorization code grant_ flow being used.

**Comment by agorman** [comment]
For the client app I can reproduce by changing the seeings under App client settings -> OAuth 2.0. Check only Authorization code grant and aws.cognito.signin.user.admin.

**Comment by tmaiaroto** [comment]
Ok, I changed the example to the more common access token. Arguably the right one to be using. If you use openid then you'd have the ID token as well. Left some comments in there, it's simply a matter of using the "proper" token (or the only one you might have I suppose depending on options).

I could get this working (with `tokens.AccessToken`) using `aws.cognito.signin.user.admin` grant alone. Let me know if there are any other configuration options that cause further issues. Thanks!
